# Generated by Django 5.0.7 on 2024-07-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_quote_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='category',
            field=models.CharField(max_length=10),
        ),
    ]
