# Generated by Django 5.0.7 on 2024-07-31 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_quote_text_rename_quote_text_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='category',
        ),
        migrations.AddField(
            model_name='text',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('simple', 'simple'), ('complex', 'complex')], max_length=10, null=True),
        ),
    ]
