# Generated by Django 5.0.7 on 2024-07-31 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_text_category_text_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='difficulty',
        ),
    ]
