# Generated by Django 5.0.7 on 2024-07-31 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_text_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='text',
            new_name='quote',
        ),
    ]
