# Generated by Django 5.0.7 on 2024-07-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_text_text_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('difficulty', models.CharField(choices=[('simple', 'simple'), ('complex', 'complex')], default=('simple', 'simple'), max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
