# Generated by Django 5.0.7 on 2024-07-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_quote_delete_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='difficulty',
            field=models.CharField(choices=[('simple', 'simple'), ('complex', 'complex')], default='simple', max_length=10),
        ),
    ]
