# Generated by Django 5.0.7 on 2024-07-31 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_quote_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='text',
            new_name='quote_text',
        ),
    ]
