# Generated by Django 5.0.7 on 2024-07-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_text_quote_quote_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='difficulty',
            field=models.CharField(choices=[('simple', 'simple'), ('complex', 'complex')], default='simple', max_length=10),
        ),
    ]
