# Generated by Django 5.0.7 on 2024-07-31 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_quote_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='difficulty',
        ),
    ]
