# Generated by Django 5.0.7 on 2024-07-31 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='difficulty',
            field=models.CharField(choices=[('simple', 'simple'), ('medium', 'medium'), ('complex', 'complex')], default='simple', max_length=10),
        ),
    ]
