# Generated by Django 5.0.7 on 2024-07-31 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_data_quote_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rank',
            name='quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.quote'),
        ),
        migrations.AddField(
            model_name='rank',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
